package com.magneticmule.toponimo.client.ui;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.content.res.Configuration;
import android.graphics.PixelFormat;
import android.os.Bundle;

import android.view.View;
import android.view.Window;
import android.view.WindowManager;

import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;

import com.facebook.android.*;
import com.facebook.android.Facebook.*;
import com.magneticmule.toponimo.client.R;
import com.magneticmule.toponimo.client.ApiKeys;

public class LoginActivity extends Activity {

	boolean		isLoggedIn	= false;

	/*
	 * requires the app key generated by the fb api, see
	 * http://developers.facebook.com/docs/guides/mobile/
	 */
	Facebook	facebook		= new Facebook(ApiKeys.FACEBOOK_API_KEY);

	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.login);

		final ImageView facebookLoginButton = (ImageView) findViewById(R.id.facebookLoginButton);
		// if the facebook button is pressed
		facebookLoginButton.setOnClickListener(new View.OnClickListener() {
			public void onClick(View v) {
				facebookLogin();
			}
		});

		// if the LOGIN button is pressed
		final Button loginButton = (Button) findViewById(R.id.loginbtn);
		loginButton.setOnClickListener(new View.OnClickListener() {

			public void onClick(View v) {
				Intent i = new Intent(LoginActivity.this, PlaceListActivity.class);
				startActivity(i);
			}
		});

		// when the Signup button is pressed
		final Button signupButton = (Button) findViewById(R.id.signupbtn);
		signupButton.setOnClickListener(new View.OnClickListener() {

			public void onClick(View v) {
				Toast toast = Toast.makeText(LoginActivity.this, "Feature pending", Toast.LENGTH_SHORT);
				toast.show();

			}
		});
	}

	@Override
	public void onConfigurationChanged(Configuration newConfig) {
		super.onConfigurationChanged(newConfig);
		setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
	}

	// Handles the facebook login screen.
	public void facebookLogin() {
		if (facebook.isSessionValid()) {
			Intent i = new Intent(LoginActivity.this, PlaceListActivity.class);
			startActivity(i);
		} else {

			/**
			 * see: http://developers.facebook.com/docs/authentication/permissions/
			 * for a full list of permissions
			 */

			facebook.authorize(this, new String[] { "user_checkins", "user_about_me", "user_birthday", "user_website", "publish_stream" },
					new DialogListener() {

						public void onComplete(Bundle values) {

						}

						public void onFacebookError(FacebookError error) {
							System.out.println("Error: " + error.getMessage().toString());
						}

						public void onError(DialogError e) {

						}

						public void onCancel() {
							// return to login screen
						}
					});
		}
	}

	@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {
		super.onActivityResult(requestCode, resultCode, data);

		facebook.authorizeCallback(requestCode, resultCode, data);
	}

	@Override
	public void onAttachedToWindow() {
		super.onAttachedToWindow();
		Window window = getWindow();
		window.setFormat(PixelFormat.RGBA_8888);
		window.addFlags(WindowManager.LayoutParams.FLAG_DITHER);
	}

}